version: "3.8"
services:
  database:
    container_name: docker_mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: B16301850b
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  backend:
    container_name: backend
    build: ./Library_Back_End
    environment:
      - spring.datasource.url=jdbc:sqlserver://docker_mssql;encrypt=true;trustServerCertificate=true;DB_CLOSE_ON_EXIT=FALSE
      - END_TO_END_TEST_IP=http://frontend:3000
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    build: ./Library_Front_End
    ports:
      - "3000:3000"